apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-signalr-affinity
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - sa.example.com
      secretName: tls-cert
  rules:
  - host: sa.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: signalr-affinity
              port:
                number: 9090
